import kit from "../../assets/pdImage.js";
const KitProducts = [
  
  {
    id: "201",
    name: "Coffee maker",
    price: 3079.99,
    description: "Brew the perfect cup of coffee with this state-of-the-art coffee maker...",
    images: [kit.coffee,kit.juicer,kit.ricemaker,kit.toaster], 
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
    
  },
  {
    id: "202",
    name: "Juicer Machine",
    price: 2659.99,
    description: "juicer machine for fresh and healthy juices...",
    images: [kit.juicer,kit.ricemaker,kit.toaster,kit.coffee],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
    
  },
   {
    id: "203",
    name: "Rice Maker",
    price: 1209.99,
    description: "rice maker for perfect and fluffy rice every time...",
    images: [kit.ricemaker,kit.toaster,kit.coffee,kit.juicer],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
   },
   {
    id: "204",
    name: "Toaster",
    price: 4206.99,
    description: "toaster for crispy and golden toast...",
    images: [kit.toaster,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
    {
    id: "205",
    name: "Ac_Container",
    price: 799.99,
    description: "ac_container for cooling and refreshing air...",
    images: [kit.ac_container,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
     {
    id: "206",
    name: "Bowl",
    price: 799.99,
    description: "bowl for serving and mixing food...",
    images: [kit.bowl,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
       {
    id: "207",
    name: "chai_cup",
    price: 799.99,
    description: "chai_cup for enjoying your favorite tea...",
    images: [kit.chai_cup,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
        {
    id: "208",
    name: "chopping_knife",
    price: 799.99,
    description: "chopping_knife for cutting and preparing food...",
    images: [kit.chopping_knife,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
         {
    id: "209",
    name: "ciger",
    price: 799.99,
    description: "ciger for slicing...",
    images: [kit.ciger,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "210",
    name: "coco_chopper",
    price: 799.99,
    description: "coco_chopper for chopping...",
    images: [kit.coco_chopper,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
          {
    id: "211",
    name: "container",
    price: 799.99,
    description: "container for storing food...",
    images: [kit.container,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "212",
    name: "dal_press",
    price: 799.99,
    description: "dal_press for pressing dal...",
    images: [kit.dal_press,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "213",
    name: "ice_makker",
    price: 799.99,
    description: "ice_makker for making ice...",
    images: [kit.ice_makker,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "214",
    name: "karai",
    price: 299.99,
    description: "karai for cooking food...",
    images: [kit.karai,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "215",
    name: "karai",
    price: 199.99,
    description: "karai for cooking food...",
    images: [kit.karai,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
          {
    id: "216",
    name: "roti_belun",
    price: 99.99,
    description: "roti_belun for cooking food...",
    images: [kit.karai,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
           {
    id: "217",
    name: "rspray",
    price: 99.99,
    description: "rspray for cooking food...",
    images: [kit.rspray,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },
             {
    id: "218",
    name: "thali",
    price: 99.99,
    description: "thali for cooking food...",
    images: [kit.thali,kit.coffee,kit.juicer,kit.ricemaker],
    colors: ["black","red", "blue"],
    size: ["S", "M", "L", "XL"],
    category: "kitchen",
  },

];
export default KitProducts;